Aiven-Open/journalpump

kafkajournalpump/kafkajournalpump.py

logging: remove useless kafka.client internal tracebacks from logging

---

Makefile
kafkajournalpump.spec
setup.py

* postgres shouldn't own /var/lib/kafkajournalpump
* fix version number in Makefile wrt git tags
* depend on python-systemd
* depend on python-kafka
* fix typos in rpm summary and description

build: fix a bunch of issues

---

README.rst
kafkajournalpump/kafkajournalpump.py
kafkajournalpump/statsd.py

Add basic statistics output to a telegraf statsd daemon.
Telegraf/InfluxDB-specific tags are used, so this will not
work with a generic statsd daemon.
Metrics sending spec:
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/statsd

stats: telegraf statsd support

---

journalpump/journalpump.py
test/test_journalpump.py

The tests didn't like not being able to initialize Elasticsearch.

journalpump: delay initialization of Elasticsearch object until needed

---

journalpump/journalpump.py

This is done so Kibana would let search be used for these values.
See https://github.com/elastic/kibana/issues/2551 for more info
on the kibana issue.

journalpump: omit underscore prefix in fields read from journal

---

NEWS
README.rst
journalpump.json
journalpump/journalpump.py
journalpump/statsd.py
test/test_journalpump.py

NOTE: This is a backward breaking change for the json configuration file
format!
* Multiple "readers" can be operated in a single journalpump process
* Each reader has its own input settings (source file, flags, metrics
tags, etc.)
* One reader can have zero or more "senders", i.e. the same journal
entries can be sent to multiple destinations (e.g. log file + Kafka)
Smaller changes:
* StatsD output is buffered, making overall performance somewhat better
* More extensive progress stats are written to the output stats file
* Output stats file is disabled unless explicitly enabled in the json
configuration file

journalpump: multiple readers and senders

---

README.rst
journalpump.json
journalpump/journalpump.py
test/test_journalpump.py

Previously all fields read from journald were always sent forward. There
are typically quite a few fields that are not interesting for specific
use cases and sending them just creates bloat.
A new field filter configuration is now supported and each sender may be
associated with a specific filter. If a sender doesn't have associated
field filter it behaves like before (sends all fields), otherwise the
appropriate filter is applied before the entry data is serialized. To
support the sender specific filtering (and to allow easier testing of
just part of the logic) the journal object processing was refactored to
a class of its own.
Both whitelist and blacklist field filters are supported. Whitelist
filters only include the explicitly specified fields while blacklist
filters only exclude the …

Allow filtering journald fields

---

debian/changelog.in
debian/control
debian/postinst
journalpump/journalpump.py
journalpump/statsd.py

This addresses all errors indicated by `lintian` and warnings other than:
```W: journalpump: binary-without-manpage usr/bin/journalpump```
I don't know if modifying the email address after-the-fact is kosher. That change can be easily dropped if so desired.

Address lintian errors and some warnings

---

journalpump/journalpump.py

Previously journald API was not used as the documentation suggests, which caused it to stop returning log messages after log rotation and possibly in some other cases as well. Switched to polling file descriptors so that we can react immediately and added the process call that is required to cope with any non-append operations.
Also changes the logic related to enforcing maximum number of messages that are kept in memory. The old implementation already had a variable controlling how many messages should be kept in memory at most but the implementation was nonsensical. Instead of doing anything to restrict the in-memory messages it slowed down message sending away from the node, which just made the problem worse. Now the journal reader is completely disabled when too many messages are in …

Use journald API more appropriately, limit log messages to keep in memory

---

.travis.yml
journalpump/journalpump.py

If searches have been defined for a given reader, only pass through messages that match those searches to senders. This allows one to output a selection of the captured messages to readers.
Previous behavior of passing full incoming stream and doing stats on searches can be accomplished by configuring two readers the searches on the first and the senders on the latter.

reader: if set, only pass through messages that match searches

---

NEWS
journalpump/journalpump.py
journalpump/util.py

The requests library by default uses indefinite timeout, which may cause
calls to block forever. The Elasticsearch code was missing timeouts from
a couple of places, which potentially caused sender thread to hang.
Also start using an adapter that explicitly sets some timeout so that
new calls added in the future don't accidentally omit the timeout.

Add missing timeouts for requests HTTP calls

---

journalpump.spec

Fedora 31 comes with an updated rpmbuild that is more picky about what
it will accept. The %{requires} macro is no longer accepted in the
BuildRequires field.

journalpump.spec: support building on Fedora 31

---

journalpump.spec

Build runs tests and tests require this package.

journalpump.spec: add python3-responses test dependency

---

journalpump/journalpump.py

Update error import due to previous location being deprecated

kafka: update member refs from deprecated/deleted file to new location

---

journalpump/journalpump.py
journalpump/util.py

The index deletion expects the list to only contain indexes created
by journalpump and fails if the list contains indexes that start
with the prefix, but are not actually created by journalpump
(logs- vs logstash).

elasticsearch: fix es index deletion logic

---

.travis.yml
Makefile
NEWS
README.rst
debian/control
journalpump.spec
journalpump/journalpump.py
test/test_journalpump.py

Adds a new sender for sending log events to AWS CloudWatch. It is possible to configure the log group and stream as well as the AWS region to be used for the sender. AWS credentials can be set in sender config. If credentials or region are left out they are configured by the `boto3` module.

aws_cloudwatch: added sender for aws cloudwatch logs

---

.travis.yml
Makefile
NEWS
README.rst
debian/control
journalpump.spec
journalpump/journalpump.py
journalpump/senders/__init__.py
journalpump/senders/google_cloud_logging.py
test/test_journalpump.py

Added new logs sender for Google Cloud Logging. Logs are labeled as `generic_node` type monitored resources and it is possible to pass in labels allowed by this type. For more info see https://cloud.google.com/monitoring/api/resources#tag_generic_node.
Requires Google Service Account type credentials. If credentials are not set in journalpump config it will attempt to find credentials from system.

google_cloud_logging: added google cloud logging sender

---

journalpump/senders/google_cloud_logging.py
test/test_journalpump.py

The `googleapiclient` was logging at `INFO` loglevel for all requests made a against the logging API. I reduced the verbosity of logging to `WARNING`.
Also, fixed the ISO8601 formatted timestamp to include timezone if it is missing. Assuming all timestamps to be UTC.

google_cloud_logging: few improvements

---

README.rst
journalpump/senders/kafka.py

Support socks5_proxy setting via configuration. Kafka-python library must support he same, and this support is currently in Aiven fork of kafka-python only.

kafka: support defining socks5_proxy

---

journalpump/senders/kafka.py

Unless explicitly provided by the user, let `KafkaProducer` infer the api version. `0.9` is old enough that using this as the default can lead to errors if some modern features are used, e.g. compression with `zstd`.

kafkasender: by default infer the api version

---

README.rst
journalpump/senders/kafka.py

Useful for clusters configured with `auto.create.topics.enable = false`.
I manually tested this with:
Journalpump `config.json`:
```json
{
"log_level": "DEBUG",
"readers": {
"host1": {
"senders": {
"kafka1": {
"output_type": "kafka",
"kafka_address": "127.0.0.1:9092",
"kafka_topic": "journals",
"kafka_topic_config": {
"num_partitions": 1,
"replication_factor": 1
}
}
}
}
}
}
```
Script `generate_event.py` to generate events:
```python
import logging
from systemd.journal import JournalHandler
log = logging.getLogger('demo')
log.addHandler(JournalHandler())
log.setLevel(logging.INFO)
log.info("sent to journal")
```
```sh
ip=$(ip -j address show wlp0s20f3 | jq '.[0].addr_info | .[] | select(.family=="inet").local' -r)
podman run --rm --env ZOOKEEPER_CLIENT_PORT=2181 -p 2181 …
```

Automatic topic creation for kafka sender

---

journalpump/journalpump.py
journalpump/senders/aws_cloudwatch.py
journalpump/senders/base.py
journalpump/senders/file.py
systest/test_rsyslog.py
test/test_journalpump.py

Journalpump would crash if `AWSCloudwatchSender` got
`AccessDeniedException` during sender init. This can
happen if there are wrong credentials in config.
All `ClientError` class AWS errors are now caught during init
and retried a few times. This will catch `AccessDeniedException`
and transient `ServiceUnavailable` errors.
`AccessDeniedException` errors are reported to `JournalReader`. 
`JournalReader` ignores senders that failed to initialize during operation.

awscloudwatchsender: fix crash due to wrong credentials

---

journalpump/__init__.py
journalpump/senders/websocket.py

This is consistent with the parameter name used by the kafka sender.
Bump version number to 2.3.7.

websocket sender: Use socks5_proxy config parameter name

---

NEWS
journalpump/__init__.py
journalpump/senders/websocket.py

Reduce effects of reconnection storms by giving more time for the handshake to complete and retry slightly less often.

websocket sender: Use a longer connection timeout and slower retries, version 2.4.1

---

journalpump/__init__.py
journalpump/senders/kafka.py
journalpump/senders/rsyslog.py

TimeoutError could be raised instead of socket.timeout
due to low values of tcp keepalive
Starting from py3.10 socket.timeout is alias to TimeoutError

Handle TimeoutError as retriable

---

README.rst
journalpump/journalpump.py
journalpump/senders/base.py
journalpump/types.py
systest/test_rotation.py
test/test_journalpump.py

This will allow specifying log level limits per unit basis in case you want to filter what log level severities journalpump picks up

journalpump: add support for unit_log_levels

---

journalpump/rsyslog.py

This pr aims to make the rsyslog sender more resilient to temporary networking issues

rsyslog: make more error codes retriable

---

README.rst
journalpump/senders/base.py
journalpump/senders/rsyslog.py
systest/test_rsyslog.py

this pr is a suggestion of adding heartbeat messages to journalpump. related note from the datadog documentation: 
```
(Optional) Datadog cuts inactive connections after a period of inactivity. Some Rsyslog versions are not able to reconnect properly when necessary. To mitigate this issue, use time markers so the connection never stops. To achieve this, add the following 2 lines in your Rsyslog configuration:
$ModLoad immark
$MarkMessagePeriod 20
And don’t forget to restart:
```
It would be nice to have the same for journalpump

base: add heartbeat messages

---

journalpump/senders/base.py

At 2^1024, an overflow exception is generated.

senders: Limit backoff multiplier to 2^100 to prevent overflow

---

journalpump/senders/base.py
journalpump/statsd.py

Prevent journalpump from getting stuck when an exception is raised. Previously, an exception which was not caught, would cause journalpump to get stuck, since the sender threads are not stopped, and they are not marked with daemon=True. Mark them as daemon, so that the main thread quitting will cause the program to quit (and get restarted by systemd).
* Tested that the "Bad message on journal read" and "OSError on stats socket write" exceptions now cause termination, not stuckness
* Tested that journalpump shutdown is still clean; the main thread will quit after websocket & kafka senders have stopped
Also catch the stats socket write error - it may happen frequently when the receiving UDP service is restarted and not available for a few seconds.

Prevent journalpump hang on exceptions

---

journalpump/senders/elasticsearch_opensearch_sender.py
test/test_elasticsearch_opensearch_sender.py
test/test_journalpump.py

- Add support ES 8.x and keep backward compatibility for ES 6.x
- Add index auto-mapping for fields in a message, so if JSON message has fields they will be
mapped automatically to the index mapping. Supported python types:
- str
- boolean
- int
- float
- dict

elasticsearch,opensearch: Add fields for index mapping

---

journalpump/journalpump.py
journalpump/senders/__init__.py
journalpump/util.py
systest/test_rotation.py
test/test_google_cloud_logging.py
test/test_journalpump.py
test/test_websocket.py

- Changes number of default imports (when running journalpump -h) from 862 to 307.
- Minimum RSS for actually journalpump doing work goes 58MB -> 35MB

Changed senders to be lazy loaded

---

journalpump/journalpump.py
test/test_journalpump.py

if unit_log_level configuration is an empty list, journalpump excludes all logs and does not ship any to a sender. this PR makes it ignore filtering if there is no config

journalpump: fix case where unit_log_level config is empty list

---

journalpump/senders/elasticsearch_opensearch_sender.py
test/test_elasticsearch_opensearch_sender.py

Fixed index url for old ES versions which needs to include
include_type_name flag

Fix index url for old ES version

---

README.rst
journalpump/journalpump.py
journalpump/senders/aws_cloudwatch.py
journalpump/senders/base.py
journalpump/statsd.py

This PR improves how metrics are emitted for tracking invalid configurations
* when configuration settings are invalid, the statsd gauge is periodically refreshed, allowing monitoring tools to more easily track the problem.
* invalid configuration settings will not cause the service to restart, though the new configuration file will be parsed when detected.
* The journalpump configuration file supports an optional statsd `prefix` value. This will be prepended to all metric names.

Capture configuration errors more cleanly

---

journalpump/senders/elasticsearch_opensearch_sender.py

`_indicies_url` for the `_EsOsLogSenderBase` class can contain sensitive
information, typically a password in the form of
`https://user:pass@host:port`. As a result, this information would be
logged should ES/OS not be available.
This commit redacts this using a standard pattern to remove this
password from being logged.

fix: redact sensitive information from indicies url when logging

---

journalpump/senders/base.py
systest/test_rotation.py
test/unit/senders/test_base.py

The tag sanitization introduced in
14a57be709cc9a5968918e0e25ea54f823c1fb5d was both too strict and too
loose. As per
https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels,
we need to make sure labels match the regexp `[a-zA-Z_:][a-zA-Z0-9_:]*`,
but `statsd` is more restrictive:
https://github.com/statsd/statsd/blob/9cf77d87855bcb69a8663135f59aa23825db9797/stats.js#L164-L172.
To solve this, lets have the tag names match strictly `[^\w_\-]+`.
For values, these can be typically any ASCII chars (as per Prometheus
above). However, the line protocol excludes the use of certain
characters, so lets ensure all characters that match `[\s\|=:]+` are
replaced.

fix: tighten up tag sanitization

---

journalpump/journalpump.py
test/test_journalpump.py

switch logic to only filter out logs if
it matches glob AND priority is higher
than the configured one - otherwise it
will just filter out everything else which is
not our intended usecase

journalpump: change logic of log-levels

---

journalpump/rsyslog.py

This reverts commit 99345ea684ce74c782d8a3b32d38aadccc68e171.
It turned out `SSLEOFError` was not the cause of the issue, so no need to retry for this particular error. This doesn't seem like a recoverable one anyway so it makes sense to reinitialize right away when the rsyslog client if `SSLEOFError` happens

Revert "rsyslog: mark some ssl errors as retriable"

---

journalpump/journalpump.py

0.5% of our M3 metrics are this with zero.

Skip secret match metric if nothing to report

---

Makefile
journalpump/senders/aws_cloudwatch.py
requirements.txt
test/test_journalpump.py

botocore dependency is simpler for the use case of `journalpump` rather than using the boto3 wrapper. This makes it easier to use it along with other dependencies.

remove boto3 dependency

---

journalpump/journalpump.py

While performing a search on an entry, cache binary fields that have been already decoded (for performance reasons).

journalpump: Decode fields only once

---

.github/workflows/build.yml
.pre-commit-config.yaml
Makefile
journalpump/senders/websocket.py
requirements.dev.txt
setup.py
test/test_websocket.py

the "standard" pylint action did not work for python 3.11 so replaced it with re-introduced `make pylint`.
Until full cleanup has been made only fail the build if pylint step finds Errors.
Mark the "known" import errors instead of blindly allowing all import errors unlike previously done in the commit hook implementation.

ci: support python 3.11

---

README.rst
journalpump/daemon.py
journalpump/journalpump.py

In the docs it says we default to null for `match_value`, however we
actually throw. This makes us gracefully handle that input as described, and updates the docs to explicitly describe that behaviour.

config: handle missing match_value as described in readme

---

journalpump/rsyslog.py

Create a default ssl context with minimum_version set to TLSv1.2. This should be nearly universally compatible and provide the best baseline level of security/compliance
`ssl.create_default_context()` is used since we require > python3.9; 
> ssl.create_default_context - a convenience function, supported in Python 3.4 and later versions.
Even when you use these alternatives, you should ensure that a safe protocol is used. The following code illustrates how to use flags (available since Python 3.2) or the `minimum_version` field (favored since Python 3.7) to restrict the protocols accepted when creating a connection.

update rsyslog TLS config

---

.gitignore
journalpump/journalpump.py
test/unit/reader/test_stats.py

https://github.com/aiven/journalpump/pull/140 Intended to limit 0 metric values to only be emitted once, but it didn't check if the preceding value was zero so continued emission of 0 could occur.

reader: correctly only emit zeros once

---

journalpump/journalpump.py
test/unit/reader/test_stats.py

#156 Attempted to fix the duplicate 0 emissions, but accidentally kept the initial 0 emission when no failures have ever occured. This corrects that test and the fix to not emit the initial 0.

reader: do not emit initial 0 on always successful configurations

---

Makefile
journalpump.spec
journalpump/senders/google_cloud_logging.py
requirements.txt
setup.py

The oauth2client was deprecated in 2019 and has not received any updates ever since. In particular, it does not support the `universe_domain` option.
> Note: oauth2client is now deprecated. No more features will be added to the
libraries and the core team is turning down support. We recommend you use
google-auth and oauthlib. For more details on the deprecation,
see oauth2client deprecation.

senders: migrate from oauth2client to google-auth

---

.github/workflows/codeql-analysis.yml

Codeql workflow needs more than just the default content:read permission

github: fix permissions for codeql integration

---

journalpump/daemon.py
journalpump/journalpump.py
journalpump/senders/elasticsearch_opensearch_sender.py
journalpump/senders/kafka.py
journalpump/senders/rsyslog.py
journalpump/senders/websocket.py

I have added some additional logging to improve traceability when working with multiple senders. Now the name of the sender in the journalpump.json is appended to Initializtion logging messages to identify which senders are having issues and which are performing correctly.
e.g in the default journalpump.json "elastic1" and "kafka1" are now easily identified despite both being in the "host1" reader config.
I also added some consistency updates to the log files to make sure they all followed the same pattern.

Logging improvements for multiple senders and consistency fixes

---

README.rst
journalpump/journalpump.py
test/test_journalpump.py

in case some bad regex search defined,
it would be easier to identify the offender
The threshold is defined as threshold_for_metric_emit with default value 10 seconds.
The metric would look like this:
with regex tag on it.

Add a threshold for search if want to emit a metric

---

journalpump/senders/base.py
test/unit/senders/test_base.py

Only include tags that have no None-valued keys/values.

senders: check tags for None keys/values

---

journalpump/senders/base.py
journalpump/senders/google_cloud_logging.py
test/test_google_cloud_logging.py

https://cloud.google.com/logging/docs/reference/v2/rest/v2/entries/write
https://cloud.google.com/logging/quotas
This PR is doing two things:
1. Not retrying to send logs that return with HTTP status code 4xx. Instead those logs are simply skipped.
2. Filtering out any `LogEntry` that is bigger than 256K

senders: Mitigate issue with GCP logging quota

---

journalpump/senders/websocket.py

In websockets v14+ the signature for `connect` has changed. We can use `client.connect` to work across this [breaking change.](https://websockets.readthedocs.io/en/stable/howto/upgrade.html)
In <v14 it will alias to the default `connect` method, and in v14+ it will use the `websockets.legacy` module ensuring compatibility. Once we pin websockets on v14+ then we can switch to using the new `connect` API.

websockets: use client.connect instead of connect

---

README.rst

This tool is being used for OpenSearch at Aiven. I did not touch / extend the CLI options that relate to Elasticsearch, as I'm not sure these changes are required.

added OpenSearch to the list of supported outputs
