kafkajournalpump/kafkajournalpump.py

Previously in case we got an error we just got stuck forever.

kafka: Reinitialize kafka if we get an exception

---

kafkajournalpump/kafkajournalpump.py

* Handle normal, expected errors during send and retry with a new client
connection
* Somewhat better error messages

kafka: retry on expected errors during send

---

kafkajournalpump/kafkajournalpump.py

We now set last_journal_msg_time after resetting the reader so we
guarantee that at most we'd get a reset per 180 seconds.
..and also set the last_journal_msg_time in the successful case
when we do actually get a log event.

kafkajournalpump: Set last_journal_msg_time in more places

---

.gitignore
.travis.yml
README.rst
debian/copyright
kafkajournalpump.spec
setup.py

python requirements: update readme and rpm spec to require python3

---

.gitignore
.travis.yml
journalpump/journalpump.py
setup.py
test/test_journalpump.py

JournalReader perform_searches() now works properly when matching against multiple fields.
Also some tiny pylint, flake8 cleanups and marking Python 3.6 as supported version.

search regular expression / tag fixes

---

journalpump/journalpump.py

Earlier change in how the journald API was used had regression in
handling situations where explicit journald directory is used and
that is not yet available.

Fix handling of cases where journald cannot be initialized yet

---

journalpump/journalpump.py

Reduce amount of logging output for normal operations, as it does not add much value to know immediately about recently sent messages, which in busy machines produce a significant amount of logging.

stats: reduce logging output

---

Makefile
NEWS
README.rst
journalpump/journalpump.py
journalpump/rsyslog.py
test/test_journalpump.py

- add reader connection state to journpump_state.json
- report current reader state to statd
- fixed rsyslog connection handling

minor improvements and fixes

---

README.rst
journalpump/journalpump.py
journalpump/rsyslog.py
systest/test_rsyslog.py

- add support for custom custom log format
- fix handling of oversized messages lines
- use default severity if PRIORITY is missing
- us default facility if SYSLOG_FACILITY is a list

rsyslog: add limited support for custom log format

---

.pylintrc
.travis.yml
Makefile
journalpump/journalpump.py
test/test_journalpump.py

- use /index/_bulk instead of /_bulk
- minor write optimization (no \n string concatenation)
- added simple UT for elasticsearchsender

3 minor commits

---

journalpump/journalpump.py

Some errors might not be caught be the maintenance_operation
implementation, causing the thread to exit. Catch and log any such
errors and retry again after a minute.

Catch errors in sender maintenance

---

journalpump/journalpump.py

enhance connection recovery and add es7 support

---

.flake8
.gitignore
.isort.cfg
.pylintrc
.style.yapf
.travis.yml
Makefile
journalpump/__init__.py
journalpump/__main__.py
journalpump/daemon.py
journalpump/geohash.py
journalpump/journalpump.py
journalpump/rsyslog.py
journalpump/senders/__init__.py
journalpump/senders/aws_cloudwatch.py
journalpump/senders/base.py
journalpump/senders/elasticsearch.py
journalpump/senders/google_cloud_logging.py
journalpump/senders/kafka.py
journalpump/senders/logplex.py
journalpump/senders/rsyslog.py
journalpump/types.py
journalpump/util.py
mypy.ini
requirements.dev.txt
requirements.txt
setup.py
systest/test_rsyslog.py
test/test_journalpump.py

Add standard Aiven linting and formatting checks.

Add Aiven standard linters and formatting

---

journalpump/daemon.py
journalpump/journalpump.py
journalpump/rsyslog.py
journalpump/util.py
test/test_journalpump.py

Close journal properly on process termination

journal: close journal on exit

---

journalpump/journalpump.py

Close the reader (journal) on a new configuration load.
It seems that `sd_journal_close` (which is called by journal reader close) is quite important and should be called whenever we don't need reader anymore. If SIGHUP is sent many times to the process over the time, it might end up in stale temp files on disk which will lead to out of space.

journal: close all journals on new configuration

---

journalpump/journalpump.py

This fixes a bug when OSError (Code 22) exception is raised on sending SIGTERM to `journalpump`.
```
journalpump           MainThread      ERROR     Unexpected exception while handling entry for instance_system_stats
Traceback (most recent call last):
File "/usr/lib/python3.7/site-packages/journalpump/journalpump.py", line 658, in read_single_message
jobject = reader.read_next()
File "/usr/lib/python3.7/site-packages/journalpump/journalpump.py", line 292, in read_next
jobject = next(self.journald_reader)
File "/usr/lib64/python3.7/site-packages/systemd/journal.py", line 224, in __next__
ans = self.get_next()
File "/usr/lib/python3.7/site-packages/journalpump/journalpump.py", line 96, in get_next
if super()._next(skip):
OSError: [Errno 22] Invalid argument
```

journal: close file descriptors in the main loop/unregister from polling

---

journalpump/senders/kafka.py

Zstandard will be the first choice for compression used, provided it's
also supported by the python client, followed by snappy, then gzip

kafka: add zstandard compression support

---

journalpump/senders/aws_cloudwatch.py
test/test_journalpump.py

Fixes an issue where having more than page size log streams inside a log group, the log stream was not found and the sequence token needed for sending logs could not be set. Now we use pagination when listing the log streams inside the log group and paginate until the correct stream is found.

aws_cloudwatch: fixed sender init to support log stream pagination

---

journalpump/senders/kafka.py

Errors in Kafka send() results were silently ignored. Python kafka library returns future, which may (eventually) contain error related to send.

kafka sender: react to kafka send errors

---

journalpump/rsyslog.py

Deprecated since version 3.7: Since Python 3.2 and 2.7.9, it is recommended to use the SSLContext.wrap_socket() instead of wrap_socket(). The top-level function is limited and creates an insecure client socket without server name indication or hostname matching.
https://docs.python.org/3/library/ssl.html#ssl.wrap_socket
PR pulls out internal logic of `ssl.wrap_socket`

rsyslog: stop using deprecated ssl.wrap_socket

---

journalpump/journalpump.py
test/test_journalpump.py

For some senders connection can't be established immidiatelly
so to prevent errors, if there is not initialized reader return
0 when queried for limits
Also there are some configurations that don't have senders for whatever reason

Handle delayed sender initialization

---

journalpump/journalpump.py
test/test_journalpump.py

Some configurations don't have senders configured, but used for a
side effect to collect stats about event occurence on the instance

Fix reader without sender configured not sending stats

---

README.rst

Add disclaimer for trademark.
Add full name to Apache Kafka in places where it made sense.

Update readme to comply with trademark rules

---

README.rst
journalpump/journalpump.py
test/test_journalpump.py

This change adds a secret filtering functionality. Config is at the reader level to allow one reader to redact secrets for multiple senders, but enable different behaviour between readers.
Provide a regex with groups, a redaction message, and define which groups are to be redacted in the case of a match. Multiple patterns can be added.

Add a secret filtering functionality to journalpump.

---

journalpump/rsyslog.py

If sending a message through syslog fails with EPIPE because the remote socket was closed we have to have a short retry mechanism. If we are not retrying the sending immediately we could continously have a situation where the socket timed out when we want to write something into it.

rsyslog: handle epipe transparently in syslog client

---

README.rst
journalpump/rsyslog.py
journalpump/senders/base.py
journalpump/senders/rsyslog.py
systest/test_rsyslog.py

this PR reverts heartbeats and a minor senders/base.py cleanup in favor of properly fixing the rsyslog reconnection logic

rsyslog: revert heartbeats and fix rsyslog reconnect

---

.github/workflows/build.yml
Makefile
README.rst
codecov.yml
requirements.dev.txt

Goal: Enable codecov coverage integration.

ci: add coverage/codecov

---

journalpump/journalpump.py

If there never was an error, sending the metric constantly is simply waste of resources.

Stop (re)sending zero failure metric

---

setup.py

We should not build a systest package as it is just tests.

setup: do not build systest
